### ISSUE TITLE
Missing file when running distill on dave

### ISSUE THREAD

**Issue by lli-debu** [edwardxu0/GDVB#23]
Hi,

I got this error msg in the logs when running  `python -m gdvb configs/dave.toml train 10`  after generated the CA.

```
(.venv) lli@SushiRoll:~/tools/GDVB/results$ cat dave.10/dis_log/dave.00443_0.132.out 
WARNING  2024-02-08 19:57:31,116 (r4v.nn) auto_pad is deprecated: (VALID)
WARNING  2024-02-08 19:57:31,144 (r4v.nn) auto_pad is deprecated: (VALID)
WARNING  2024-02-08 19:57:31,173 (r4v.nn) auto_pad is deprecated: (VALID)
WARNING  2024-02-08 19:57:31,198 (r4v.nn) auto_pad is deprecated: (VALID)
WARNING  2024-02-08 19:57:31,216 (r4v.nn) auto_pad is deprecated: (VALID)
Process Process-1:
Traceback (most recent call last):
  File "/home/lli/anaconda3/envs/gdvb/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lli/anaconda3/envs/gdvb/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lli/tools/GDVB/lib/R4V/r4v/distillation/__init__.py", line 190, in distill
    train_loader = get_data_loader(config.data.train)
  File "/home/lli/tools/GDVB/lib/R4V/r4v/distillation/data.py", line 323, in get_data_loader
    return udacity_driving(data_config)
  File "/home/lli/tools/GDVB/lib/R4V/r4v/distillation/data.py", line 367, in udacity_driving
    data_config.teacher.path, data_config.student.path, transforms=[teacher_transform,student_transform]
  File "/home/lli/tools/GDVB/lib/R4V/r4v/distillation/data.py", line 128, in __init__
    with open(interpolated_csv) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/udacity.sdc.100/training/interpolated.csv'
```

It looks like the training data is missing for dave? 
For `mnist_tiny' the training data directory appears as soon as I start the training, but this is not the case for dave.
Could you tell me where to fetch the traning data? Thanks.

Linhan

**Comment by edwardxu0** [comment]
Hi, GDVB_v2 has just been released. You should use GDVB v2. It contains the training data for Dave2. Go to the data folder and unzip the file. Let me know if you have other questions.
