### ISSUE TITLE
Files not created in ./results/mnist_tiny.10/dis_model/

### ISSUE THREAD

**Issue by WissaGdr** [edwardxu0/GDVB#6]
Hello,

After running the following command `python -m gdvb configs/mnist_tiny.toml train 10`, the corresponding result files were not created in the mentioned folder ./results/mnist_tiny.10/dis_model. Any idea why is that happening?

Wissal

**Comment by edwardxu0** [comment]
Did you follow the instructions to complete all dependencies? Including the ACTS CA generator?

**Comment by wissalgdr** [comment]
Yes, I followed the exact instructions on the instruction area, and I was able to generate the Mix Covering Array "ca.txt", also.
 As you can see from the attached screenshot, the NN-training is done successfully. But, the folder is empty. Moreover, I get this stack trace

Traceback (most recent call last):
  File "/home/wg/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wg/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wg/Documents/GDVB/lib/R4V/r4v/__main__.py", line 6, in <module>
    from . import cli
  File "/home/wg/Documents/GDVB/lib/R4V/r4v/cli/__init__.py", line 5, in <module>
    from .. import distillation
  File "/home/wg/Documents/GDVB/lib/R4V/r4v/distillation/__init__.py", line 11, in <module>
    from .data import get_data_loader
  File "/home/wg/Documents/GDVB/lib/R4V/r4v/distillation/data.py", line 12, in <module>
    from torchvision.datasets.folder import (
ImportError: cannot import name 'find_classes' from 'torchvision.datasets.folder' (/home/wg/Documents/GDVB/.venv/lib/python3.8/site-packages/torchvision/datasets/folder.py)

**Comment by edwardxu0** [comment]
Based on your error log, I believe the issues are caused by using your own customized environment with the wrong dependencies. I see that you are using python 3.8 and anaconda.

If you follow the exact steps in the installation instructions. It will create a virtual environment for you using python3.6 and venv. You don't need to install the dependencies on your own. After installation, use `. .env.d/openenv.sh` to activate the env and run commands such as `python -m gdvb configs/mnist_tiny.toml gen_ca 10`.

I just did a fresh install of GDVB using the exact instructions in the readme on a Ubuntu 18.04 machine and it just works.

Hope this helps. Let me know if it works.

**Comment by WissaGdr** [comment]
I followed the documentation on a fresh installation  (VM) of ubuntu 18.04. I had the same outcome. and the following error message ( python 3.6) was well used.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "_main_", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bim/Documents/GDVB-master/lib/R4V/r4v/_main_.py", line 6, in <module>
    from . import cli
  File "/home/bim/Documents/GDVB-master/lib/R4V/r4v/cli/_init_.py", line 5, in <module>
    from .. import distillation
  File "/home/bim/Documents/GDVB-master/lib/R4V/r4v/distillation/_init_.py", line 11, in <module>
    from .data import get_data_loader
  File "/home/bim/Documents/GDVB-master/lib/R4V/r4v/distillation/data.py", line 12, in <module>
    from torchvision.datasets.folder import (
ImportError: cannot import name 'find_classes'

**Comment by edwardxu0** [comment]
Thank you for your comment. I think the problem is that the latest version of DNNV isn't compatible with GDVB v1.3. I am working on a newer version of GDVB and will be soon available in a couple of days. I will let you know when it is released.
